### ISSUE TITLE
groonga-keyring package missing for Debian buster

### ISSUE THREAD

**Issue by andersk** [groonga/packages.groonga.org#16]
The `groonga-keyring` package is present in the `squeeze`, `wheezy`, `jessie`, and `stretch` repositories, but it’s missing in the `buster` repository. Without this package, there’s no way to get automatic updates to the repository signing key, so `apt update` starts failing for the whole system when the key changes. Can this package be added to `buster`?

**Comment by kenhys** [comment]
Thank you for feedback @andersk  

Instead of installing keyring package, please following the instruction for updates on buster.
Here is the documentation in #buster section about details

http://groonga.org/docs/install/debian.html#buster

**Comment by andersk** [comment]
Those directions will install the key once, but will require manual intervention from the system administrator when the key changes. For Zulip we can’t expect the administrator to give that kind of low-level attention to each of our dependencies. We need an automated way to make sure the key stays updated and `apt update` doesn’t mysteriously stop working. The `groonga-keyring` package is a way to make sure that happens. Why is it being deprecated?

**Comment by kenhys** [comment]
At first, `groonga-keyring` package is aimed to install with `apt-get install --allow-insecure-repositories`, this reduces a step to download deb and install manually.

After a while, `--allow-insecure-repositories` option is removed from apt because of making apt secure, so it seems that it is good enough to use signed-by in apt-line. This is the reason why `groonga-keyring` is deprecated.

In point of view of the system administrator, it may be reasonable to make sure the key stays updated  ( by `groonga-keyring` package ), but there was no such a request at that time from users.

Is it better to recommend download `groonga-keyring `  deb and install with dpkg process for Groonga users?

**Comment by andersk** [comment]
Yeah, users tend not to complain until things actually break. Which is why I’m here now. :slightly_smiling_face:

As far as Zulip is concerned, we’ll consider this solved as long as a `groonga-keyring` package is available, and you can document whatever you think is best.

If you want my advice, I would suggest that `wget` and `dpkg -i` on `groonga-keyring_*.deb` is a good approach to document, with a couple small changes:

* The package should install all keys to a single keyring file (rather than putting new keys in separate files like `groonga-keyring-rsa4096.gpg`), so that migrations don’t break the `deb [signed-by=…]` line.
* The package should not invoke `apt-key` in `postinst`, since that isn’t necessary with `[signed-by=…]` and makes uninstallation less clean.

**Comment by kenhys** [comment]
Thank you for your advice!!!

As you suggested, It seems better to improve keyring package itself, so we will update it after a while.

**Comment by kou** [comment]
We provide `groonga-archive-keyring`: https://packages.groonga.org/debian/groonga-archive-keyring-latest-buster.deb

It configures apt-line for Groonga and installs the latest GPG keys. If we update our GPG keys, users can update `groonga-archive-keyring` by `apt upgrade`.
